apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Business Process Store
    uid: business-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: poc_business
    secureJsonData:
      password: $BUSINESS_DB_PASSWORD
    jsonData:
      database: poc_business
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    editable: false
